#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🐶 husky script: [pre-push]"
npm run script:update_markdown
git add .
git commit --amend --no-edit
echo "✅ husky script: [pre-push]"
echo ""

